# mqtt 核心配置
mind:
  monitor:
    # 是否启用健康监控，若想关闭，此处设为false即可
    enable: true
  mqtt:
    broker:
      host: 127.0.0.1
      id: mqtt-broker-1
      # 此账号密码用于管理员登录，其它客户端建议通过mind管理平台创建账号进行连接
      username: admin
      password: admin
      keep-alive: 60
      port: 1883
      # 传输模式linux上开启会有更高的性能
      use-epoll: false

# redis 配置
redisson:
  # 是否集群
  cluster: false
  # 数组格式，参考<yml配置数组>，若开启集群模式，最少配置3个节点
  address:
    - redis://192.168.41.128:6379
  # 连接超时时间
  connect-timeout: 3
  # 密码
  password: 123456
  # redis数据库序号,只有单机模式下生效
  database: 3
  # 传输模式 linux上开启会有更高的性能
  use-epoll: ${mind.mqtt.broker.use-epoll}

# 日记配置
logging:
  file:
    name: logs/${spring.application.name}/${spring.application.name}
  logback:
    rollingpolicy:
      max-history: 3
  level:
    mind.mqtt: debug
