mind:
  mqtt:
    broker:
      host: 127.0.0.1
      id: mind-mqtt-1
      keep-alive: 60
      port: 1883
      so-backlog: 511
      use-epoll: false

# 日记配置
logging:
  file:
    name: logs/${spring.application.name}/${spring.application.name}
  logback:
    rollingpolicy:
      max-history: 3
  level:
    mind.mqtt: debug
